# Generated by Django 6.0.2 on 2026-08-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_event_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='events.event')),
            ],
            options={
                'verbose_name': 'Дистанция',
                'verbose_name_plural': 'Дистанции',
            },
        ),
    ]
