# Generated by Django 6.0.2 on 2026-08-28 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventdistance'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GOING', 'Еду'), ('THINKING', 'Думаю')], default='GOING', max_length=20, verbose_name='Статус')),
                ('looking_for_company', models.BooleanField(default=False, verbose_name='Ищет компанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('distance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='events.eventdistance', verbose_name='Дистанция')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='events.event', verbose_name='Ивент')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='users.clubmember', verbose_name='Участник клуба')),
            ],
            options={
                'verbose_name': 'Участие в ивенте',
                'verbose_name_plural': 'Участия в ивентах',
                'constraints': [models.UniqueConstraint(fields=('member', 'event'), name='unique_member_event_participation')],
            },
        ),
    ]
