# Generated by Django 6.0.2 on 2026-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventparticipation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('source', 'external_id'), name='unique_event_source_external_id'),
        ),
        migrations.AddConstraint(
            model_name='eventdistance',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('event', 'external_id'), name='unique_event_event_external_id'),
        ),
    ]
