# Generated by Django 6.0.2 on 2026-09-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_external_id_event_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdistance',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
