# Generated by Django 6.0.2 on 2026-09-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventdistance_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='source_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
