# Generated by Django 6.0.2 on 2026-09-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='begin_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало события'),
        ),
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание событий'),
        ),
        migrations.AddField(
            model_name='event',
            name='timezone_offset',
            field=models.IntegerField(blank=True, null=True, verbose_name='Смещение часового пояса'),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='discipline_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='discipline_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='hide_race_date',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventdistance',
            name='race_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
