# Generated by Django 6.0.2 on 2026-09-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_begin_datetime_event_end_datetime_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventDistance',
            new_name='EventActivity',
        ),
    ]
