# Generated by Django 6.0.2 on 2026-09-17 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rename_eventdistance_eventactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactivity',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='events.event'),
        ),
    ]
