# Generated by Django 6.0.2 on 2026-09-17 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_eventactivity_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventparticipation',
            name='distance',
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to='events.eventactivity', verbose_name='Активность'),
        ),
    ]
