# Generated by Django 6.0.2 on 2026-10-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_eventactivity_options_event_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('DNF', 'DNF')], default='OPEN', max_length=200, verbose_name='Статус'),
        ),
    ]
