# Generated by Django 6.0.2 on 2026-02-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('NOT_PAID', 'Not Paid'), ('REFUND', 'Refund')], default='NOT_PAID', verbose_name='Payment Status'),
        ),
    ]
