# Generated by Django 6.0.2 on 2026-02-15 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_discount_alter_order_payment_status'),
        ('stock', '0002_alter_product_size_alter_product_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.stocklocation'),
        ),
    ]
