# Generated by Django 6.0.2 on 2026-02-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_stock_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Archive Order',
                'verbose_name_plural': 'Archive Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
