# Generated by Django 6.0.2 on 2026-02-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveTask',
            fields=[
            ],
            options={
                'verbose_name': 'Archive Task',
                'verbose_name_plural': 'Archive Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tasks.task',),
        ),
    ]
