# Generated by Django 6.0.2 on 2026-08-31 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('CONSENT', 'Согласие'), ('POLICY', 'Политика'), ('TERMS', 'Правила / условия'), ('OTHER', 'Другой документ')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('requires_acceptance', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='legal_documents/')),
                ('external_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('slug', 'version'), name='unique_legal_document_version')],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='users.clubmember')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='legal.legaldocument')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'document'), name='unique_member_document_consent')],
            },
        ),
    ]
