# Generated by Django 6.0.2 on 2026-02-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEDAL', 'Medal'), ('SOCKS', 'Socks'), ('ACCESSORY', 'Accessory'), ('DRINKWARE', 'Drinkware'), ('OTHER', 'Other'), ('CLOTHES', 'Clothes')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('variant', models.CharField(max_length=200, null=True)),
                ('size', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocklocation')),
            ],
            options={
                'unique_together': {('product', 'location')},
            },
        ),
    ]
