# Generated by Django 6.0.2 on 2026-02-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_product_size_alter_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'verbose_name': 'Остаток', 'verbose_name_plural': 'Остатки'},
        ),
        migrations.AlterModelOptions(
            name='stocklocation',
            options={'verbose_name': 'Точка склада', 'verbose_name_plural': 'Точки склада'},
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('MEDAL', 'Medal'), ('SOCKS', 'Socks'), ('ACCESSORY', 'Accessory'), ('DRINKWARE', 'Drinkware'), ('OTHER', 'Other'), ('CLOTHES', 'Clothes')], max_length=20, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Вариант'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stocklocation', verbose_name='Точка склада'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='stocklocation',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название точки'),
        ),
    ]
