server {
    listen 80;
    server_name runwithlove.site www.runwithlove.site;
    

    location /.well-known/acme-challenge/ {
	 root /var/www/certbot;

    }

    location / {
	 return 301 https://$host$request_uri;

     }
}

server {
    listen 443 ssl http2;
    server_name runwithlove.site www.runwithlove.site;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://web:8000;
	 
    ssl_certificate     /etc/letsencrypt/live/runwithlove.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/runwithlove.site/privkey.pem;

    client_max_body_size 25m;

    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 30d;
    }

    location / {
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 120s;
        proxy_connect_timeout 30s;
    }
}
