# Generated by Django 6.0.2 on 2026-02-14 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_city'),
        ('imports', '0001_initial'),
        ('orders', '0002_remove_orderitem_discount_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawexcelrow',
            name='linked_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='linked_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
