# Generated by Django 6.0.2 on 2026-02-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_alter_rawexcelrow_linked_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='file',
            field=models.FileField(default=1, upload_to='imports/'),
            preserve_default=False,
        ),
    ]
