# Generated by Django 6.0.2 on 2026-02-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_importbatch_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='result',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
