# Generated by Django 6.0.2 on 2026-02-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_importbatch_error_importbatch_processed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='NEW', max_length=20),
        ),
    ]
