# Generated by Django 6.0.2 on 2026-02-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_client_options_alter_client_address_and_more'),
        ('events', '0002_alter_event_options_alter_event_city_and_more'),
        ('imports', '0005_alter_importbatch_status'),
        ('orders', '0005_alter_archiveorder_options_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importbatch',
            options={'verbose_name': 'Пакет импорта', 'verbose_name_plural': 'Пакеты импорта'},
        ),
        migrations.AlterModelOptions(
            name='rawexcelrow',
            options={'verbose_name': 'Строка Excel (raw)', 'verbose_name_plural': 'Строки Excel (raw)'},
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='error',
            field=models.TextField(blank=True, default='', verbose_name='Ошибка'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Ивент'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file',
            field=models.FileField(upload_to='imports/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file_hash',
            field=models.CharField(max_length=255, verbose_name='Хеш файла'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='file_name',
            field=models.CharField(max_length=255, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Обработан'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='result',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='importbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imports.importbatch', verbose_name='Пакет импорта'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Текст ошибки'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='linked_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Связанный клиент'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='linked_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Связанный заказ'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='raw_data',
            field=models.JSONField(verbose_name='Сырые данные'),
        ),
        migrations.AlterField(
            model_name='rawexcelrow',
            name='row_number',
            field=models.IntegerField(verbose_name='Номер строки'),
        ),
    ]
