name: ci test

on:
  push:
    branches: ["club-calendar"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django check
        run: python manage.py check

      - name: Django tests
        run: python manage.py test --settings=config.settings_test