name: CI

on:
  push:
    branches: ["club-calendar"]

permissions:
  contents: read
  packages: write


jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Django check
        run: python manage.py check

      - name: Django tests
        run: python manage.py test --settings=config.settings_test




  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: $${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/urffin-juss/rwl_crm:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ghcr.io/urffin-juss/rwl_crm:${{ github.sha }}

