name: Dev_Deploy

on:
  push:
    branches: ["dev_deploy"]

permissions:
  contents: read
  packages: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ghcr.io/urffin-juss/rwl_crm:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ghcr.io/urffin-juss/rwl_crm:${{ github.sha }}

      - name: Prepare SSH
        run: |
          
          mkdir -p ~/.ssh
          
          chmod 700 ~/.ssh
          
          echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_ed25519
          
          chmod 600 ~/.ssh/id_ed25519
          
          echo "[${{ secrets.DEV_HOST }}]:${{ secrets.DEV_PORT }} ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBnVi2TXGVUEBFbXaWnaZc6htfpOQL2EDeUAsjCNF/46" > ~/.ssh/known_hosts
          
          chmod 644 ~/.ssh/known_hosts 


      - name: Test SSH connection
        run: |
          ssh \
            -i ~/.ssh/id_ed25519 \
            -p "${{ secrets.DEV_PORT }}" \
            "${{ secrets.DEV_USER }}@${{ secrets.DEV_HOST }}" \
            "whoami && hostname && docker ps --format 'table {{.Names}}\t{{.Status}}'"